title: "Introduction to Git and GitHub"
remote_theme: ubc-library-rc/rc-workshop-template
color_scheme: "nil"
search_enabled: false
aux_links:
  "UBC Library Research Commons Workshops":
    - "https://researchcommons.library.ubc.ca/workshops/"
heading_anchors: false
footer_content: "<a href=\"https://github.com/ubc-library-rc/intro-git/\">View workshop content in GitHub</a>"
